:ben := (base64-encode-string "ben:227spain")

#
# write keyevents
#
POST http://localhost:3000/api/keyevents/raw
Content-Type: application/json
Authorization: Basic :ben

{
    "keyevents": [{"key1": "a",
                   "key2": "b",
                   "delay": 1000000},
                   {"key1": "x",
                    "key2": "y",
                    "delay": 2000000},
                   {"key1": "x",
                    "key2": "y",
                    "delay": 2000000}],
    "start": "2020-05-03T19:40:00Z",
    "end": "2020-05-03T19:29:00Z"
}

#
# read keyevents as json
#
GET http://localhost:3000/api/keyevents/raw
Content-Type: application/json
Authorization: Basic :ben

#
# read keyevents as csv
#
GET http://localhost:3000/api/keyevents/sincor
Content-Type: application/csv
Authorization: Basic :ben

#
# calculate sincor
#
GET http://localhost:3000/api/keyevents/sincor
Content-Type: application/json
Authorization: Basic :ben

#
# read buckets
#
GET http://localhost:3000/api/buckets
Content-Type: application/json
Authorization: Basic :ben

#
# create users
#
POST http://localhost:3000/admin-api/users
Content-Type: application/json
Authorization: Basic :ben
X-Pterotype-Api-Key: mysupersecretkey

{
    "users": [{"name": "sarah",
               "password": "secret"}]
}

#
# gui
#
GET http://localhost:3000/
